server:
  port: 8086

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: 101119
    driver-class-name: org.postgresql.Driver

#  CREATE TABLE tbl_user(
#  id BIGSERIAL PRIMARY KEY,
#  username VARCHAR,
#  password VARCHAR,
#  full_name VARCHAR,
#  image_url VARCHAR,
#  birthday TIMESTAMP,
#  gender VARCHAR
#  );